# Generated by Django 4.2.3 on 2023-09-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='id_of_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='start_up_bids',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.categories'),
        ),
    ]
