# Generated by Django 4.2.3 on 2023-09-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_auction_listings_id_of_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='auction_listings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auction_listings',
            name='id_of_owner',
        ),
        migrations.RemoveField(
            model_name='auction_listings',
            name='image',
        ),
        migrations.RemoveField(
            model_name='auction_listings',
            name='start_up_bids',
        ),
        migrations.RemoveField(
            model_name='auction_listings',
            name='status',
        ),
        migrations.RemoveField(
            model_name='auction_listings',
            name='title',
        ),
    ]
