# Generated by Django 4.2.3 on 2023-09-06 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_listings_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='Creating_company',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.categories'),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='color',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='description',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='id_of_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='image',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='start_up_bids',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='title',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
