# Generated by Django 4.2.3 on 2023-09-08 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_creating_company_auction_listings_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='wath_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
