# Generated by Django 4.2.3 on 2023-09-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_listings_wath_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listings',
            old_name='wath_list',
            new_name='watch_list',
        ),
    ]
