# Generated by Django 4.2.3 on 2023-09-08 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_wath_list_auction_listings_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_comment', to='auctions.auction_listings'),
        ),
        migrations.AddField(
            model_name='comment',
            name='the_comment',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
