# Generated by Django 4.2.3 on 2023-09-13 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_list_comment_the_comment_comment_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='start_up_bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.bids'),
        ),
    ]
