# Generated by Django 4.2.3 on 2023-09-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bids_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categories_name',
            field=models.CharField(default='none', max_length=40),
        ),
    ]
